### ISSUE TITLE
Make table responsive (issue with many columns)

### ISSUE THREAD

**Issue by mynameisfreedom** [bogdancondorachi/kirby-table-field#10]
Hi @bogdancondorachi, thank you for the amazing plugin! Great work 👏

There is one thing that would be great to be improved. If you add more than 7-8 columns everything gets very narrow and stacked. Not to mention what happens with more than that. 

I experimented a bit and added the code below to the custom panel CSS

```
.k-table {
    overflow-x: auto;
}
.k-table table {
  table-layout: auto;
}
.k-table thead th {
  position: inherit;
}
.k-table thead .k-table-column, .k-table-field .k-table tbody .k-table-column {
  min-width: 120px;
}
```

Please test it out and tell me what you think. 🙂

Although this is a fast code, I can't figure out why `.k-table-index-column` changes width during hover on body cells. Maybe you can help. 

Anyway, thank you! 🙏

**Comment by bogdancondorachi** [comment]
Hi @mynameisfreedom, thank you for your kind words! :)

Indeed responsiveness is a known limitation that makes it hard to have more than 5 columns... an experimental workaround has been in the works to try and find a solution but didn't find the time to conclude it.

My approach would be to make the columns scrollable while `index-column` and `options-column` stay sticky in place, an idea that I've taken from here: [https://codepen.io/estelle/pen/RJpreX](https://codepen.io/estelle/pen/RJpreX)

Unfortunately, I can't say when I'll have it done as I'm also thinking of integrating a completely separate table component as the `.k-table` starts to fall out of this plugin's needs. In the meantime please feel free to experiment and give some feedback around what would be the best user experience in this case.

**Comment by mynameisfreedom** [comment]
Hi @gbdesign2023, thanks for the hints.

> You can deactivate the jump effect with the following additional CSS:

Yeah, yesterday was a quick and dirty solution. I tested it more now. 
Solved the hover/jumping now with

```
.k-table thead .k-table-index-column, .k-table tbody .k-table-index-column {
  min-width: 58px;
}
```

> Unfortunately, this hides the row options. This is the right-hand column with the "..."
> 
> It is therefore not the perfect solution for displaying wide columns scrollable.

Ah, didn't see that at all yesterday.
Solved it now with

```
.k-table-field .k-table thead .k-table-options-column,
.k-table-field .k-table tbody .k-table-options-column {
  display: block;
}
```

**Comment by mynameisfreedom** [comment]
Hi @bogdancondorachi, great to see you are already thinking about it. 💪

> My approach would be to make the columns scrollable while `index-column` and `options-column` stay sticky in place, an idea that I've taken from here: https://codepen.io/estelle/pen/RJpreX
> 
> Unfortunately, I can't say when I'll have it done as I'm also thinking of integrating a completely separate table component as the `.k-table` starts to fall out of this plugin's needs. In the meantime please feel free to experiment and give some feedback around what would be the best user experience in this case.

Thanks for the hints, I got this solution working now https://streamable.com/g37mez (link expires in two days)

This is the code
```
.k-table {
  overflow-x: scroll;
}
.k-table table {
  table-layout: auto;
}
.k-table thead th {
  position: inherit;
}
.k-table-field .k-table tr > :first-child {
  position: -webkit-sticky;
  position: sticky; 
  background: var(--table-color-th-back);
  left: 0; 
  z-index: 3;
}
.k-table-field .k-table table th:last-child,
.k-table-field .k-table table td:last-child {
  background: var(--table-color-th-back);
}
.k-table-field .k-table thead .k-table-options-column,
.k-table-field .k-table tbody .k-table-options-column {
  display: block;
}
.k-table thead .k-table-index-column, .k-table tbody .k-table-index-column {
  min-width: 58px;
}
.k-table thead .k-table-column, .k-table-field .k-table tbody .k-table-column {
  min-width: 120px;
}
```

So, first column is sticky, it is responsive, and everything works. The last column can't be sticky without Javascript.

It is a rough and fast solution, but I am happy with it at the moment. Thank you!

**Comment by bogdancondorachi** [comment]
Hi @mynameisfreedom, found some time to work on the responsiveness of the field, here's the first look. There are still some minor details that I need to fix but overall it looks pretty solid. I'm looking to do a pre-release of it in the following days.


https://github.com/bogdancondorachi/kirby-table-field/assets/39380741/b55d9347-c55f-4a6f-ac8d-073a4d211555

**Comment by mynameisfreedom** [comment]
Hi @bogdancondorachi, that looks great! 

Now you got complete solution 💪

**Comment by bogdancondorachi** [comment]
@mynameisfreedom @gbdesign2023 I've added the changes for responsiveness to the repo, before a release would be nice if you guys would install and give the `dev-main` a try. Mostly I'm concerned about the `min-width` of the columns as I can't think of a good solution of a good fit in all screen scenarios.

`composer require bogdancondorachi/kirby-table-field:dev-main`

**Comment by mynameisfreedom** [comment]
Hi @bogdancondorachi !

I just tested `dev-main` and it works great. On mobile and tablet also, everything is as expected. From my point of view now is perfect. 💪 Until we all manage to find a solution to also merge specific columns. 🙂 But that's another topic. 

Great work! 🚀

**Comment by gbdesign2023** [comment]
Hey @bogdancondorachi 
🎉 That's a great and very useful update. I have just tested it on my project, where I have many tables and the cells often contain long content. The scroll function is just right here. 🥇 You've turned a small gadget into a convenient tool. Many thanks for that. 🔮 I'm already looking forward to the next updates.

**Comment by bogdancondorachi** [comment]
Thank you both for your contribution/support on this matter. Has been added in the latest release! 😃
