### ISSUE TITLE
Writer marks bar is partially hidden

### ISSUE THREAD

**Issue by gbdesign2023** [bogdancondorachi/kirby-table-field#17]
If the content of a cell is formatted with writer marks, the bar is partially hidden. 
This should always be completely visible or aligned to the left.

![table](https://github.com/bogdancondorachi/kirby-table-field/assets/140849227/7335395a-c3a5-4789-8757-2bfa866ec4f2)

- Kirby 4.3 
- Table Field 2.3.2

**Comment by bogdancondorachi** [comment]
@gbdesign2023 It's happening cause of the `overflow: auto` required for the responsiveness

At the moment the least I could do is fixing it's position in order to prevent this.
