### ISSUE TITLE
Add caption ability

### ISSUE THREAD

**Issue by yatil** [bogdancondorachi/kirby-table-field#18]
Captions help users to distinguish between different tables, which is especially important for users who use assistive technologies and in situations where there are multiple tables in a document.

[See this tutorial on captions.](https://www.w3.org/WAI/tutorials/tables/caption-summary/#identifying-a-table-using-a-caption)

The caption should allow for inline formatting.

**Comment by bogdancondorachi** [comment]
@yatil Thanks on the feedback! I've added caption to block and will be included in the next replease.
