### ISSUE TITLE
The save button is only displayed after leaving the input field.

### ISSUE THREAD

**Issue by gbdesign2023** [bogdancondorachi/kirby-table-field#2]
**Standard behavior**: If changes are made in a regular input field, the orange-colored "save"-button is displayed immediately. Even without leaving the input field.
 
With a table, the "save"-button is only displayed when the input field is exited.

**Problem**: If only one value is changed quickly, this "delayed" behavior can irritate the editor in his usual workflow, as he expects the "save"-button to appear immediately.

**Comment by bogdancondorachi** [comment]
Hmm, I can't seem to replicate the issue.
I know of this behavior on the initial plugin but now it should detect changes on type.

Make sure to use the latest version or provide a video demonstration if this persists.

**Comment by gbdesign2023** [comment]
I had already installed 2.1. Just downloaded it again and now it works as expected. Are there two different 2.1 versions?
But now I have the problem that the version number is mixed up.
<img width="446" alt="version-nr" src="https://github.com/bogdancondorachi/kirby-table-field/assets/140849227/c0ec44aa-781c-414c-b948-06630efffb29">

**Comment by bogdancondorachi** [comment]
So it works as expected now?

I know of the version issue of not specifying 2.1.0 as the latest. Can't say why but hopefully will be fixed with a new release.

**Comment by gbdesign2023** [comment]
Yes, your plug-in now works as expected. You can therefore close my issue.
Sometimes the reasons for errors are not obvious. Just like the sudden disappearance of errors ;-)

There is already a discussion about the version number problem in the forum:
https://forum.getkirby.com/t/plugin-version-in-panel/30396/7

**Comment by bogdancondorachi** [comment]
Thanks for pointing me out on the issue. Feel free to reopen this if the input issue 'reapear' :)
