### ISSUE TITLE
Bug: Duplicated row synchronizes itself

### ISSUE THREAD

**Issue by gbdesign2023** [bogdancondorachi/kirby-table-field#21]
When I duplicate a row and edit the content, the content is synchronized with the original row. 
I suspect that the ID is also duplicated, which causes the unwanted behaviour.

- **Browser:** Chrome
- **Plugin Version:** 2.4.0
- **Kirby Version:** 4.5.0

https://github.com/user-attachments/assets/d3a81999-e31b-4567-bb1b-49b035609751

The red and blue badges are for the spellchecker. Please don't be distracted by them.

**Comment by bogdancondorachi** [comment]
I've released a patch that fixes this issue
