### ISSUE TITLE
Field Method toTable(): return a empty Array?

### ISSUE THREAD

**Issue by Werbschaft** [bogdancondorachi/kirby-table-field#3]
Is there a problem with the Field Method `toTable()`? No matter what I try, I always get a empty array. I have watched the Field Method and found this:

```php
if (!is_string($field->value())) {
  return ['headers' => [], 'rows' => []];
}
```
Does that make sense? Seems like the content of the field is not interpreted as String, so it always return that empty array. Good to know: it's in a Block, haven't tested in $page

```php
Array
(
    [headers] => Array
        (
        )

    [rows] => Array
        (
        )
)
```

If I remove the Field Method, I get my object back

```php
Kirby\Content\Field Object
(
    [tabelle] => Array
        (
            [0] => Array
                (
                    [0] => 'Head'
                    [1] => 'Head'
                )

            [1] => Array
                (
                    [0] => 'Content'
                    [1] => 'Content'
                )
        )
)
```

**Comment by bogdancondorachi** [comment]
@Werbschaft Unfortunately this works just as a field and there's no blocks support ATM but will come eventually in a future update. I haven't even tested it as a block but if you have a solution, a PR is welcomed.

**Comment by bogdancondorachi** [comment]
@Werbschaft I've looked a bit inside a block implementation. Could you replace the following in the method and give it a test?

> ```php
> if (!is_string($field->value())) {
>   return ['headers' => [], 'rows' => []];
> }
> ```

with this:

```php
$value = $field->value();
if (!is_string($value)) {
  $value = is_array($value) ? $value : [];
  $headers = array_shift($value);
  $rows = $value;
        
  return ['headers' => $headers, 'rows' => $rows];
}
```

**Comment by Werbschaft** [comment]
Ok, now I get a correct array back. There's only one really strange thing. I can't loop through the array. Your Demo Code does also not work.
```php
dump($table['headers']);
Array
(
    [0] => 'My Header'
    [1] => 'My Header'
)
```
When I try to loop through:
```php
foreach ( $table['headers'] as $header ) {
  dump($header);
}
```
I got the response "foreach() argument must be of type array|object, null given". Am I stupid?

**Comment by bogdancondorachi** [comment]
Ok, please try the following:

```php
$value = $field->value();
if (!is_string($value)) {
  $value = is_array($value) ? $value : [];
  $headers = !empty($value) ? array_shift($value) : [];
  $rows = $value;
        
  return ['headers' => $headers, 'rows' => $rows];
}
```

**Comment by Werbschaft** [comment]
Now it's working 🥳 I have created a pull request, I hope I have done it correct, I'm really bad at Github ...

**Comment by bogdancondorachi** [comment]
There is no need, this would be added on the next release somewhere next week. Thanks for testing this out! :)

**Comment by Werbschaft** [comment]
All right, I only want to help. Thanks for that great Plugin!

**Comment by frankziski** [comment]
i was struggling with a similar issue when using the table plugin as a block. I helped myself by the following code, based on your answers here because the toTable Function only creates an array with no keys:

`  <?php 
    $value = $block->table()->value();
    $headers = null;
    $rows = null;

    if (!is_string($value)) {
      $value = is_array($value) ? $value : [];
      $headers = array_shift($value);
      $rows = $value;
    }
  ?>
  <?php if($value != null): ?>
    <table>
      <thead>
        <tr>
          <?php foreach ($headers as $header): ?>
            <th><?= $header ?></th>
          <?php endforeach ?>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($rows as $row): ?>
          <tr>
            <?php foreach ($row as $cell): ?>
              <td><?= $cell ?></td>
            <?php endforeach ?>
          </tr>
        <?php endforeach ?>
      </tbody>
    </table>
  <?php endif ?>
`

**Comment by bogdancondorachi** [comment]
@Werbschaft @frankziski This should be fixed in the latest release.

**Comment by cafecitopuro** [comment]
Hi, I am having the same problem as above (`toTable()` function returning an empty array when using the plugin as a block), even though I am using the latest release.
