### ISSUE TITLE
Enhancement: Vue.js Block Table Preview

### ISSUE THREAD

**Issue by Werbschaft** [bogdancondorachi/kirby-table-field#6]
When I started using your field, I only used it within blocks. I quickly missed a preview that shows me at a glance which table is which.

I once created a plugin for the Vue.js preview in the panel. Maybe you'll like it and integrate something similar at some point. I can send you the code, but I think you can do it 100 times better than me 🙈, it only need 4-5 lines. Here is a preview, adapted to my options. Of course only an enhancement.

![Kapture 2024-01-30 at 16 42 08](https://github.com/bogdancondorachi/kirby-table-field/assets/2178466/3fb29ac2-7d4a-4431-8181-ed022c6e00a6)

**Comment by bogdancondorachi** [comment]
With the #3 fix on blocks, I've also started on a preview as well so I could add a full blocks integration in the next release.

My approuch was a simple preview of the field, your's seems more based on customisations based on personal needs. Though it looks fantactic, I'm not sure what would be a balanced integration.

I'd would appreciate if you can share code for further inspiration.

**Comment by bogdancondorachi** [comment]
Thanks @Werbschaft for providing your code.

In the latest release I've implemented the table block as core and it also comes with a simple table preview with inline edit. In your case, you can customize it based on your needs. I know it's pretty simple ATM but would be improved with time when I'll have some time to create a new table component that can be reused between the field and block.

You can check the current block implementation [here](https://github.com/bogdancondorachi/kirby-table-field?tab=readme-ov-file#blocks-usage)
