### ISSUE TITLE
No display of the table in mobile mode.

### ISSUE THREAD

**Issue by gbdesign2023** [bogdancondorachi/kirby-table-field#9]
The table is not displayed in the mobile view and can only be recognized as a narrow bar. If the table is opened in the editor, the display is also defective here. 

Tested under Chrome 121 for macOS

<img width="487" alt="table-hidden-1" src="https://github.com/bogdancondorachi/kirby-table-field/assets/140849227/00e4155a-7fde-4432-88b2-86f690cfd07b">

<img width="499" alt="table-hidden-2" src="https://github.com/bogdancondorachi/kirby-table-field/assets/140849227/acc4c46b-d66c-4e04-9d7c-46e896b2c766">

**Comment by gbdesign2023** [comment]
And here is another video of the error.

https://github.com/bogdancondorachi/kirby-table-field/assets/140849227/5c9a5825-42a6-4a1d-9430-73a2f52c910c

**Comment by bogdancondorachi** [comment]
@gbdesign2023 Thanks for reporting this. I'll investigate this and come up with a fix in the coming days.

Regarding the align request I can easily make it possible inside the panel but it won't reflect in the rendered table on page.

**Comment by gbdesign2023** [comment]
Since it is generally difficult to edit tables on mobile devices, I don't see any urgency in rushing to fix the error with the breakpoint. 

Yes, I mean only the display in the panel. In the backend, I add the alignment of the columns in the template.

**Comment by bogdancondorachi** [comment]
This has been fixed in the latest patch release. It includes an `align` prop for setting the text alignment :)
